### ISSUE TITLE
Add a try except block in main.py

### ISSUE THREAD

**Issue by divi-259** [Swarnendu0123/pokedex_img_converter#1]
Below are few examples of the kind of exceptions that can arise -
- File not found exception
- Some permission issue
- Library PIL throwing some exception if it is not able to process the image correctly

We can handle this case by adding a try except block.

**Comment by Swarnendu0123** [comment]
If you want to work on the issue and fix it, you are always welcome. Just solve the issue and open a pull request

**Comment by divi-259** [comment]
Can you assign this to me?
