### ISSUE TITLE
Downloading the image on entering the pokemon name and saving it to the poke-dex folder

### ISSUE THREAD

**Issue by InquisitiveMe15** [Swarnendu0123/pokedex_img_converter#24]
Currently there are only 5-6 images in the poke-dex folder, if the user wants any other pokemon image then he will just input the name and the file will be downloaded.

**Comment by InquisitiveMe15** [comment]
Currently there are only 5- images in the poke-dex folder, if the user wants any other pokemon image then he will just input the name and the file will be downloaded.

**Comment by harshkasat** [comment]
@InquisitiveMe15, since the issue has been merged, you can go ahead and close it.
